class NVMLError(Exception): ...

class DeviceHandle: ...

class MemoryInfo:
    total: int
    free: int
    used: int

def nvmlInit() -> None: ...
def nvmlShutdown() -> None: ...
def nvmlDeviceGetCount() -> int: ...
def nvmlDeviceGetHandleByIndex(index: int) -> DeviceHandle: ...
def nvmlDeviceGetMemoryInfo(handle: DeviceHandle) -> MemoryInfo: ...
